### ISSUE TITLE
python

### ISSUE THREAD

**Issue by zc616427** [BillWang139967/zabbix_manager#1]
请问使用的python版本是多少，我用的3.4.3执行main.sh报错File "./lib_zabbix/zabbix_api.py", line 37
    print "\033[41;37m[Error]: %s \033[0m"%msg
                                         ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by BillWang139967** [comment]
python的版本是2.6的，python3的版本中的print函数修改了
