### ISSUE TITLE
ImportError: No module named w_lib.zabbix_api_lib

### ISSUE THREAD

**Issue by tonys111** [BillWang139967/zabbix_manager#11]
zabbix_api user_get --table
Traceback (most recent call last):
  File "/bin/zabbix_api", line 16, in <module>
    from w_lib.zabbix_api_lib import ZabbixAPI
ImportError: No module named w_lib.zabbix_api_lib
一直都找不到这个模块，不知道什么原因？请教大神，求回复，谢谢，

**Comment by meetbill** [comment]
建议重新 clone 下，并重新执行安装下试下

如还出现上面情况:
可检查下 /opt/ZabbixTool/lib_zabbix/w_lib/ 目录下是否有 zabbix_api_lib.py

**Comment by meetbill** [comment]
查看下 /opt/ZabbixTool/lib_zabbix/config.py 是否存在
