### ISSUE TITLE
关于zabbix_api 的ssl配置问题

### ISSUE THREAD

**Issue by Nginx1** [BillWang139967/zabbix_manager#17]
zabbix_server="https://%s:%s"%(self.server,self.port)
修改完之后报错
w_lib.zabbix_api_lib.ZabbixAPIException: urllib2.URLError - [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)

**Comment by meetbill** [comment]
网站的 SSL 证书是经过 CA 认证的吗？还是自己生成的？

**Comment by Nginx1** [comment]
> 网站的 SSL 证书是经过 CA 认证的吗？还是自己生成的？

自己生成的

**Comment by meetbill** [comment]
将 ZabbixTool/lib_zabbix/zabbix_api.py:80 行的
```
self.zapi=ZabbixAPI(server=zabbix_server)
改为

self.zapi=ZabbixAPI(server=zabbix_server,validate_certs=False)
```

试试

**Comment by Nginx1** [comment]
> 将 ZabbixTool/lib_zabbix/zabbix_api.py:80 行的
> 
> ```
> self.zapi=ZabbixAPI(server=zabbix_server)
> 改为
> 
> self.zapi=ZabbixAPI(server=zabbix_server,validate_certs=False)
> ```
> 
> 试试

感谢，但是修改完成之后出现了报错
w_lib.zabbix_api_lib.ZabbixAPIException: urllib2.URLError - Not Found
我现在修改了
zabbix_server="https://%s:%s"%(self.server,self.port)
self.zapi=ZabbixAPI(server=zabbix_server,validate_certs=False
apache = True

**Comment by meetbill** [comment]
好的，现在是可以正常使用了是吧

**Comment by Nginx1** [comment]
> 好的，现在是可以正常使用了是吧

是的，谢谢！
