### ISSUE TITLE
zabbix_api --report item_name date_from date_till

### ISSUE THREAD

**Issue by wuhongtao2016** [BillWang139967/zabbix_manager#2]
1.2.2
[Error]: 时间格式 ['2016-05-01 00:00:00'] ['2016-06-01 00:00:00'] 

报表运行的时候报错.

**Comment by wuhongtao2016** [comment]
zabbix_api --report "CPU" '2016-03-24 00:00:00' '2016-03-25 00:00:00'

**Comment by BillWang139967** [comment]
@wuhongtao2016 您执行的方式是什么？貌似您的时间格式有点问题

**Comment by wuhongtao2016** [comment]
zabbix_api --report "CPU idle time" "2016-06-03 00:00:00" "2016-06-10 00:00:00"

**Comment by wuhongtao2016** [comment]
有什么问题？ 目前没有排查出来。

**Comment by BillWang139967** [comment]
@wuhongtao2016 您的zabbix版本是多少？执行程序时可以通过加参数`-d`输出调试信息

**Comment by wuhongtao2016** [comment]
zabbix 版本是这个2.4.5。
调试的话走到时间那就报错了
![Uploading image.png…]()
 11

**Comment by wuhongtao2016** [comment]
有些基础的模块是可以用的比如。组、主机

**Comment by wuhongtao2016** [comment]
解决了日期了，又出现其他问题。

**Comment by wuhongtao2016** [comment]
w_lib.zabbix_api_lib.ZabbixAPIException: (u'Error -32602: Invalid params., Incorrect API "trend". while sending {"params": {"output": ["itemid", "clock", "num", "value_min", "value_avg", "value_max"], "time_till": 1490371200, "time_from": 1490284801, "limit": "8760", "itemids": "24088"}, "jsonrpc": "2.0", "method": "trend.get", "auth": "2e7b3dc74bf9cb6b1f464c64f5feafb9", "id": 1}', -32602)

**Comment by BillWang139967** [comment]
@wuhongtao2016 zabbix_manage是根据zabbix3.0的接口写的，2.4的话，相应接口可能有些改动

**Comment by wuhongtao2016** [comment]
我们只用发送报表的？需要改哪里，能提示一下吗

**Comment by BillWang139967** [comment]
@wuhongtao2016 zabbix3.0 新增了trend接口，使用2.4的话，需要编写一个函数替换zabbix_api.py中的__trend_get函数，此函数是输出一段时间内某个item的最大值，平均值，最小值

**Comment by BillWang139967** [comment]
@wuhongtao2016 zabbix会收集历史数据(history_get获取)，以及还会收集每小时的平均数据作为趋势数据(trend_get)，每小时才收集一次，所以trends(趋势)占用的资源很小。这样的话，2.4需要通过history_get输出一段时间内某个item的最大值，平均值，最小值，【注意:需要注意history的保留时间】

**Comment by wuhongtao2016** [comment]
有点困难，我在找找别的有没有同样的开源的吧。谢谢了
