### ISSUE TITLE
能否多个监控项一起添加

### ISSUE THREAD

**Issue by hubeixulu** [BillWang139967/zabbix_manager#3]
非常感谢你能写这个工具，能否导出报表的时候添加多个监控项呢，就像添加多个主机组一样

**Comment by BillWang139967** [comment]
@hubeixulu 
[zabbix manager 使用手册](https://github.com/BillWang139967/zabbix_manager/wiki)

您好，导出报表时，可以使用正则表达式或者application的方式输出不同的key

**Comment by hubeixulu** [comment]
@BillWang139967 感谢解答，昨天捐了5块钱表示感谢

**Comment by BillWang139967** [comment]
@hubeixulu 多谢捐助
