### ISSUE TITLE
报错？centos7,python2.7

### ISSUE THREAD

**Issue by ld1978** [BillWang139967/zabbix_manager#5]
报错？centos7,python2.7
[root@localhost zabbix_manager]# zabbix_api hostgroup_get --table
zabbix_manager:[1.4.01]
Traceback (most recent call last):
  File "/usr/bin/zabbix_api", line 2530, in <module>
    zabbix=zabbix_api(terminal_table,debug,output_sort=output_sort,sort_reverse=sort_reverse,profile = profile)
  File "/usr/bin/zabbix_api", line 81, in __init__
    self.zapi.login(self.user,self.password)
  File "/opt/ZabbixTool/lib_zabbix/w_lib/zabbix_api_lib.py", line 209, in login
    result = self.do_request(obj)
  File "/opt/ZabbixTool/lib_zabbix/w_lib/zabbix_api_lib.py", line 260, in do_request
    return self.do_request(json_obj,num_retries-1) 
  File "/opt/ZabbixTool/lib_zabbix/w_lib/zabbix_api_lib.py", line 260, in do_request
    return self.do_request(json_obj,num_retries-1) 
  File "/opt/ZabbixTool/lib_zabbix/w_lib/zabbix_api_lib.py", line 260, in do_request
    return self.do_request(json_obj,num_retries-1) 
  File "/opt/ZabbixTool/lib_zabbix/w_lib/zabbix_api_lib.py", line 265, in do_request
    raise ZabbixAPIException("urllib2.URLError - %s" % e)
w_lib.zabbix_api_lib.ZabbixAPIException: urllib2.URLError - Not Found

**Comment by BillWang139967** [comment]
您好，是使用的 apache 吗？

**Comment by BillWang139967** [comment]
https://github.com/BillWang139967/zabbix_manager/issues/4

**Comment by ld1978** [comment]
是的。apache2.4.6

**Comment by ld1978** [comment]
配置完apache=True，还报以下错误，像是缺少模块。
[root@localhost MySQL-python-1.2.5]# zabbix_api hostgroup_get --table
Traceback (most recent call last):
  File "/usr/bin/zabbix_api", line 16, in <module>
    from w_lib.zabbix_api_lib import ZabbixAPI
  File "/opt/ZabbixTool/lib_zabbix/w_lib/zabbix_api_lib.py", line 1
    e This is a port of the ruby zabbix api found here:

**Comment by BillWang139967** [comment]
@ld1978 可以查看/opt/ZabbixTool/lib_zabbix/w_lib/zabbix_api_lib.py 第一行是否进行过修改，正常此行应该是注释状态。

**Comment by ld1978** [comment]
[root@zabbix zabbix_manager]# cat /opt/ZabbixTool/lib_zabbix/w_lib/zabbix_api_lib.py 
# This is a port of the ruby zabbix api found here:
# http://trac.red-tux.net/browser/ruby/api/zbx_api.rb
#
# LGPL 2.1   http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html
# Zabbix API Python Library.
# Original Ruby Library is Copyright (C) 2009 Andrew Nelson nelsonab(at)red-tux(dot)net
# Python Library is Copyright (C) 2009 Brett Lentz brett.lentz(at)gmail(dot)com
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA


# NOTES:
# The API requires zabbix 1.8 or later.
# Currently, not all of the API is implemented, and some functionality is
# broken. This is a work in progress.

# meetbill

import base64
import hashlib
import logging
import string
import sys
import ssl
import socket
try:
    import urllib2
except ImportError:
    import urllib.request as urllib2  # python3
import re
from collections import deque

try:
    from ssl import _create_unverified_context
    HAS_SSLCONTEXT = True
except ImportError:
    HAS_SSLCONTEXT = False


default_log_handler = logging.StreamHandler(sys.stdout)
__logger = logging.getLogger("zabbix_api")
__logger.addHandler(default_log_handler)
__logger.log(10, "Starting logging")

try:
    # Separate module or Python <2.6
    import simplejson as json
    __logger.log(15, "Using simplejson library")
except ImportError:
    # Python >=2.6
    import json
    __logger.log(15, "Using native json library")


def checkauth(fn):
    """ Decorator to check authentication of the decorated method """

    def ret(self, *args):
        self.__checkauth__()
        return fn(self, args)
    return ret


def dojson(fn):
    def wrapper(self, method, opts):
        self.logger.log(logging.DEBUG,
                "Going to do_request for %s with opts %s"
                % (repr(fn), repr(opts)))
        return self.do_request(self.json_obj(method, opts))['result']
    return wrapper


class ZabbixAPIException(Exception):

    """ generic zabbix api exception
    code list:
         -32602 - Invalid params (eg already exists)
         -32500 - no permissions
    """
    pass


class Already_Exists(ZabbixAPIException):
    pass


class InvalidProtoError(ZabbixAPIException):

    """ Recived an invalid proto """
    pass


class APITimeout(ZabbixAPIException):
    pass


class ZabbixAPI(object):
    __username__ = ''
    __password__ = ''

    auth = ''
    url = '/api_jsonrpc.php'
    params = None
    method = None
    # HTTP or HTTPS
    proto = 'http'
    # HTTP authentication
    httpuser = None
    httppasswd = None
    timeout = 10
    validate_certs = None
    # sub-class instances.
    # Constructor Params:
    # server: Server to connect to
    # path: Path leading to the zabbix install
    # proto: Protocol to use. http or https
    # We're going to use proto://server/path to find the JSON-RPC api.
    #
    # user: HTTP auth username
    # passwd: HTTP auth password
    # log_level: logging level
    # r_query_len: max len query history
    # **kwargs: Data to pass to each api module

    def __init__(self, server='http://localhost/zabbix', user=httpuser, passwd=httppasswd,
                 log_level=logging.WARNING, timeout=10, r_query_len=10, validate_certs=True, **kwargs):
        """ Create an API object.  """
        self._setuplogging()
        self.set_log_level(log_level)
        self.server = server
        self.url = server + '/api_jsonrpc.php'
        self.proto = self.server.split("://")[0]
        # self.proto=proto
        self.httpuser = user
        self.httppasswd = passwd
        self.timeout = timeout
        self.kwargs = kwargs
        self.id = 0
        self.r_query = deque([], maxlen=r_query_len)
        self.validate_certs = validate_certs
        self.debug(logging.INFO, "url: " + self.url)

    def _setuplogging(self):
        self.logger = logging.getLogger("zabbix_api.%s" % self.__class__.__name__)

    def set_log_level(self, level):
        self.debug(logging.INFO, "Set logging level to %d" % level)
        self.logger.setLevel(level)

    def recent_query(self):
        """
        return recent query
        """
        return list(self.r_query)

    def debug(self, level, var="", msg=None):
        strval = str(level) + ": "
        if msg:
            strval = strval + str(msg)
        if var != "":
            strval = strval + str(var)

        self.logger.log(level, strval)

    def json_obj(self, method, params={}, auth=True):
        obj = {'jsonrpc': '2.0',
               'method': method,
               'params': params,
               'auth': self.auth,
               'id': self.id}
        if not auth:
            del obj['auth']

        self.debug(logging.DEBUG, "json_obj: " + str(obj))

        return json.dumps(obj)

    def login(self, user='', password='', save=True):
        if user != '':
            l_user = user
            l_password = password

            if save:
                self.__username__ = user
                self.__password__ = password
        elif self.__username__ != '':
            l_user = self.__username__
            l_password = self.__password__
        else:
            raise ZabbixAPIException("No authentication information available.")

        # don't print the raw password.
        hashed_pw_string = "md5(" + hashlib.md5(l_password.encode('utf-8')).hexdigest() + ")"
        self.debug(logging.DEBUG, "Trying to login with %s:%s" %
                (repr(l_user), repr(hashed_pw_string)))
        obj = self.json_obj('user.login', {'user': l_user, 'password': l_password}, auth=False)
        result = self.do_request(obj)
        self.auth = result['result']

    def test_login(self):
        if self.auth != '':
            obj = self.json_obj('user.checkAuthentication', {'sessionid': self.auth})
            result = self.do_request(obj)

            if not result['result']:
                self.auth = ''
                return False  # auth hash bad
            return True  # auth hash good
        else:
            return False

    def do_request(self, json_obj,num_retries=3):
        headers = {'Content-Type': 'application/json-rpc',
                   'User-Agent': 'python/zabbix_api'}

        if self.httpuser:
            self.debug(logging.INFO, "HTTP Auth enabled")
            auth = 'Basic ' + string.strip(base64.encodestring(self.httpuser + ':' + self.httppasswd))
            headers['Authorization'] = auth
        self.r_query.append(str(json_obj))
        self.debug(logging.INFO, "Sending: " + str(json_obj))
        self.debug(logging.DEBUG, "Sending headers: " + str(headers))

        request = urllib2.Request(url=self.url, data=json_obj.encode('utf-8'), headers=headers)
        if self.proto == "https":
            if HAS_SSLCONTEXT and not self.validate_certs:
                https_handler = urllib2.HTTPSHandler(debuglevel=0, context=_create_unverified_context())
            else:
                https_handler = urllib2.HTTPSHandler(debuglevel=0)
            opener = urllib2.build_opener(https_handler)
        elif self.proto == "http":
            http_handler = urllib2.HTTPHandler(debuglevel=0)
            opener = urllib2.build_opener(http_handler)
        else:
            raise ZabbixAPIException("Unknow protocol %s" % self.proto)

        urllib2.install_opener(opener)
        try:
            response = opener.open(request, timeout=self.timeout)
        except ssl.SSLError as e:
            if hasattr(e, 'message'):
                e = e.message
            raise ZabbixAPIException("ssl.SSLError - %s" % e)
        except socket.timeout as e:
            raise APITimeout("HTTP read timeout",)
        except urllib2.URLError as e:
            if num_retries>0:  
                return self.do_request(json_obj,num_retries-1) 
            if hasattr(e, 'message') and e.message:
                e = e.message
            elif hasattr(e, 'reason'):
                e = e.reason
            raise ZabbixAPIException("urllib2.URLError - %s" % e)
        self.debug(logging.INFO, "Response Code: " + str(response.code))

        # NOTE: Getting a 412 response code means the headers are not in the
        # list of allowed headers.
        if response.code != 200:
            raise ZabbixAPIException("HTTP ERROR %s: %s"
                    % (response.status, response.reason))
        reads = response.read()
        if len(reads) == 0:
            raise ZabbixAPIException("Received zero answer")
        try:
            jobj = json.loads(reads.decode('utf-8'))
        except ValueError as msg:
            print ("unable to decode. returned string: %s" % reads)
            sys.exit(-1)
        self.debug(logging.DEBUG, "Response Body: " + str(jobj))

        self.id += 1

        if 'error' in jobj:  # some exception
            msg = "Error %s: %s, %s while sending %s" % (jobj['error']['code'],
                    jobj['error']['message'], jobj['error']['data'], str(json_obj))
            if re.search(".*already\sexists.*", jobj["error"]["data"], re.I):  # already exists
                raise Already_Exists(msg, jobj['error']['code'])
            else:
                raise ZabbixAPIException(msg, jobj['error']['code'])
        return jobj

    def logged_in(self):
        if self.auth != '':
            return True
        return False

    def api_version(self, **options):
        obj = self.do_request(self.json_obj('apiinfo.version', options, auth=False))
        return obj['result']

    def __checkauth__(self):
        if not self.logged_in():
            raise ZabbixAPIException("Not logged in.")

    def __getattr__(self, name):
        return ZabbixAPISubClass(self, dict({"prefix": name}, **self.kwargs))


class ZabbixAPISubClass(ZabbixAPI):

    """ wrapper class to ensure all calls go through the parent object """
    parent = None
    data = None

    def __init__(self, parent, data, **kwargs):
        self._setuplogging()
        self.debug(logging.INFO, "Creating %s" % self.__class__.__name__)
        self.data = data
        self.parent = parent

        # Save any extra info passed in
        for key, val in kwargs.items():
            setattr(self, key, val)
            self.debug(logging.WARNING, "Set %s:%s" % (repr(key), repr(val)))

    def __getattr__(self, name):
        if self.data["prefix"] == "configuration" and name == "import_":  # workaround for "import" method
            name = "import"

        def method(*opts):
            return self.universal("%s.%s" % (self.data["prefix"], name), opts[0])
        return method

    def __checkauth__(self):
        self.parent.__checkauth__()

    def do_request(self, req):
        return self.parent.do_request(req)

    def json_obj(self, method, param):
        return self.parent.json_obj(method, param)

    @dojson
    @checkauth
    def universal(self, **opts):
        return opts

**Comment by ld1978** [comment]
发现可以了，你这个太牛X了。可以加个qq不，崇拜啊。

**Comment by BillWang139967** [comment]
@ld1978 209094373

**Comment by dyangel16** [comment]
hi.您好，我遇到一样的报错，是nginx请问怎么解决的@ld1978

**Comment by dyangel16** [comment]
抱歉。报错不一样，
root@Zabbix zabbix_tool]#  zabbix_api dev_hosts_info --table
zabbix_manager:[1.4.03]
Traceback (most recent call last):
  File "/usr/bin/zabbix_api", line 2546, in <module>
    zabbix=zabbix_api(terminal_table,debug,output_sort=output_sort,sort_reverse=sort_reverse,profile = profile)
  File "/usr/bin/zabbix_api", line 81, in __init__
    self.zapi.login(self.user,self.password)
  File "/opt/ZabbixTool/lib_zabbix/w_lib/zabbix_api_lib.py", line 209, in login
    result = self.do_request(obj)
  File "/opt/ZabbixTool/lib_zabbix/w_lib/zabbix_api_lib.py", line 260, in do_request
    return self.do_request(json_obj,num_retries-1)
  File "/opt/ZabbixTool/lib_zabbix/w_lib/zabbix_api_lib.py", line 260, in do_request
    return self.do_request(json_obj,num_retries-1)
  File "/opt/ZabbixTool/lib_zabbix/w_lib/zabbix_api_lib.py", line 260, in do_request
    return self.do_request(json_obj,num_retries-1)
  File "/opt/ZabbixTool/lib_zabbix/w_lib/zabbix_api_lib.py", line 265, in do_request
    raise ZabbixAPIException("urllib2.URLError - %s" % e)
w_lib.zabbix_api_lib.ZabbixAPIException: urllib2.URLError - Not Found
[root@Zabbix zabbix_tool]#

**Comment by dyangel16** [comment]
[root@Zabbix zabbix_tool]# curl -i http://127.0.0.1:80/zabbix/api_jsonrpc.phpHTTP/1.1 412 Precondition Failed
Server: nginx/1.6.0
Date: Tue, 14 Nov 2017 12:57:05 GMT
Content-Type: text/html
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Methods: POST
Access-Control-Max-Age: 1000

[root@Zabbix zabbix_tool]#

**Comment by BillWang139967** [comment]
nginx 的话不需要加，apache 部分不需要设置为true

**Comment by dyangel16** [comment]
搭建的zabbix,地址是http://127.0.0.1/zabbx/，通过curl -i http://IP:端口/zabbix/api_jsonrpc.php 命令，返回HTTP/1.1 412 Precondition Failed 添加认证返回是正确的。
这是我 zabbix_tool/zabbix_config.ini配置，请问是否正确
[zabbixserver]
server = 127.0.0.1
port = 80
user = admin
password = zabbix

**Comment by BillWang139967** [comment]
配置文件:/etc/zabbix_tool/zabbix_setting.ini

修改如下

apache=True

**Comment by dyangel16** [comment]
@BillWang139967 不好意思，没说清楚，使用nginx搭建的，试过apache=True 试过更改zabbix_config.ini server地址，返回都是报错。

**Comment by BillWang139967** [comment]
将127.0.0.1 换成zabbix_server的实际IP试试

**Comment by dyangel16** [comment]
您好。依旧
>w_lib.zabbix_api_lib.ZabbixAPIException: urllib2.URLError - Not Found
会和我的安装环境有关吗。我的zabbix,地址是http://127.0.0.1/zabbx/
 可是在 zabbix_tool/zabbix_config.ini ,server项写上/127.0.0.1/zabbx/也依旧not found

**Comment by dyangel16** [comment]
您好。已经OK了，谢谢，把zabbix网页前端 直接放在nginx下就可以了

**Comment by BillWang139967** [comment]
好的

**Comment by jasonjiangxinhui** [comment]
我也遇到同样的问题了，我是通过修改 /opt/ZabbixTool/lib_zabbix/w_lib/zabbix_api_lib.py 
文件当中114 行添加了zabbixurl    url = 'zabbix/api_jsonrpc.php' 解决的。 感谢前辈

**Comment by jasonjiangxinhui** [comment]
不过我测试，导出保存文件和excel 有问题，保存不了。保存-f 文件为0不写入。excel指定了，找到excel文件。环境是pyton 2.7, zabbix 5.0 。

**Comment by meetbill** [comment]
导出  excel 时日志或者终端有什么报错吗？

**Comment by jasonjiangxinhui** [comment]
没有任何报错

[root@cdntjcmtest01-cache01 ~]#  zabbix_api history_get 35979 "2021-05-01 00:00:00" "2021-05-01 00:10:00"  --xls /tmp/test.xls
zabbix_manager:[1.4.04]
35979 35040273144 2021-05-01 00:04:39
35979 36908302592 2021-05-01 00:09:39
[root@cdntjcmtest01-cache01 ~]# ll /tmp/
total 3392
drwx------. 2 root root     24 Dec  7 03:21 ssh-sByEEs9Udrl7
drwx------. 3 root root     17 Dec  7 03:21 systemd-private-cfaad781dd8f4f49ae04ea768f156c3f-bolt.service-MYAGyu
drwx------. 3 root root     17 Dec  7 03:21 systemd-private-cfaad781dd8f4f49ae04ea768f156c3f-chronyd.service-625Pmb
drwx------. 3 root root     17 Dec  7 03:21 systemd-private-cfaad781dd8f4f49ae04ea768f156c3f-colord.service-cv7DJO
drwx------. 3 root root     17 Dec  7 03:21 systemd-private-cfaad781dd8f4f49ae04ea768f156c3f-cups.service-oY33ay
drwx------. 3 root root     17 Dec  7 03:21 systemd-private-cfaad781dd8f4f49ae04ea768f156c3f-fwupd.service-WLNooZ
drwx------. 3 root root     17 May 26 15:16 systemd-private-cfaad781dd8f4f49ae04ea768f156c3f-httpd.service-Wgh2Bs
drwx------. 3 root root     17 Dec  7 03:21 systemd-private-cfaad781dd8f4f49ae04ea768f156c3f-mariadb.service-y5e54S
drwx------. 3 root root     17 Dec  7 03:21 systemd-private-cfaad781dd8f4f49ae04ea768f156c3f-rh-php72-php-fpm.service-sHoKCd
drwx------. 3 root root     17 Dec  7 03:21 systemd-private-cfaad781dd8f4f49ae04ea768f156c3f-rtkit-daemon.service-gt0L99
-rw-------. 1 root root 313815 May 16 06:24 yum_save_tx.2021-05-16.06-24.2p6Wg4.yumtx
-rw-------. 1 root root 313815 May 17 06:24 yum_save_tx.2021-05-17.06-24.JC4s8r.yumtx
-rw-------. 1 root root 313815 May 18 06:24 yum_save_tx.2021-05-18.06-24.5VGsl3.yumtx
-rw-------. 1 root root 313815 May 19 06:24 yum_save_tx.2021-05-19.06-24.0rh6Ja.yumtx
-rw-------. 1 root root 313815 May 20 06:23 yum_save_tx.2021-05-20.06-23.E1XAtX.yumtx
-rw-------. 1 root root 313815 May 21 06:23 yum_save_tx.2021-05-21.06-23.GokZEl.yumtx
-rw-------. 1 root root 313815 May 22 06:23 yum_save_tx.2021-05-22.06-23.Rdpx4s.yumtx
-rw-------. 1 root root 313815 May 23 06:23 yum_save_tx.2021-05-23.06-23.mYOqRJ.yumtx
-rw-------. 1 root root 313815 May 24 06:23 yum_save_tx.2021-05-24.06-23.F_kZsL.yumtx
-rw-------. 1 root root 313815 May 25 06:23 yum_save_tx.2021-05-25.06-23.0RM3WJ.yumtx
-rw-------. 1 root root 313815 May 26 06:22 yum_save_tx.2021-05-26.06-22.0LkLkK.yumtx
-rw-r--r--. 1 root root      1 May 26 16:43 zabbix_tool.log
[root@cdntjcmtest01-cache01 ~]# cat /tmp/zabbix_tool.log 

[root@cdntjcmtest01-cache01 ~]#

**Comment by meetbill** [comment]
history_get 方法不支持导出 xls，只是里面部分方法支持导出 xls :)

**Comment by jasonjiangxinhui** [comment]
好吧。谢谢
